# Generated by Django 5.2.8 on 2025-11-23 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("products_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("discount_message", models.CharField(blank=True, max_length=100)),
                ("contact_info", models.CharField(blank=True, max_length=100)),
                ("delivery_info", models.CharField(blank=True, max_length=200)),
                ("call_to_action", models.CharField(blank=True, max_length=100)),
                ("original_image", models.ImageField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="thumbnails/%Y/%m/%d/"),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("square", "Square (1080x1080) - Instagram"),
                            ("portrait", "Portrait (1080x1920) - Stories"),
                            ("landscape", "Landscape (1920x1080) - General"),
                        ],
                        default="square",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_key", "-created_at"],
                        name="flyers_prod_session_2c1d65_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_name", models.CharField(max_length=50)),
                ("design_file", models.ImageField(upload_to="designs/%Y/%m/%d/")),
                ("is_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="flyers.product",
                    ),
                ),
            ],
            options={
                "ordering": ["template_name"],
            },
        ),
    ]
