# Generated by Django 5.2.8 on 2025-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flyers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="original_image",
            field=models.ImageField(max_length=500, upload_to="uploads/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=500, upload_to="thumbnails/%Y/%m/%d/"
            ),
        ),
    ]
