# Generated by Django 5.2.8 on 2025-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flyers", "0002_alter_product_original_image_alter_product_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="call_to_action",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="contact_info",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_info",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_message",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=10, null=True
            ),
        ),
    ]
