# Generated by Django 5.2.8 on 2025-11-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flyers", "0003_alter_product_call_to_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generateddesign",
            name="times_selected",
            field=models.IntegerField(default=0),
        ),
    ]
