# Generated by Django 5.2.8 on 2025-11-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flyers", "0004_generateddesign_times_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="remove_background",
            field=models.BooleanField(
                default=False,
                help_text="Remove background from product image for better design effects",
            ),
        ),
    ]
